
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* 여기에 직접 script 태그 삽입 */}
        <script
          src="https://klicklab-sdk.pages.dev/klicklab_sdk.js"
          data-sdk-key="f2719562-c64d-4175-aa3e-b66caad59d79"
        ></script>
       
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< Updated upstream
        <Navbar />
        {children}
=======

        <CartProvider>
          <WishlistProvider>
            <OrderProvider>
              <Navbar />
              {children}
            </OrderProvider>
          </WishlistProvider>
        </CartProvider>

>>>>>>> Stashed changes
      </body>
    </html>
  );
}
